# Generated by Django 4.1.7 on 2023-04-02 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=40)),
                ('editora', models.CharField(max_length=30)),
                ('data_cadastro', models.DateField()),
                ('edicao', models.CharField(max_length=30)),
                ('ano_edicao', models.DateTimeField()),
                ('categoria', models.CharField(max_length=50)),
                ('emprestado', models.BooleanField(default=False)),
                ('description', models.TextField()),
            ],
        ),
    ]
